// This script will run at build time to inject environment variables
window.ENV_FIREBASE_API_KEY = '{{FIREBASE_API_KEY}}';
window.ENV_FIREBASE_AUTH_DOMAIN = '{{FIREBASE_AUTH_DOMAIN}}';
window.ENV_FIREBASE_PROJECT_ID = '{{FIREBASE_PROJECT_ID}}';
window.ENV_FIREBASE_STORAGE_BUCKET = '{{FIREBASE_STORAGE_BUCKET}}';
window.ENV_FIREBASE_MESSAGING_SENDER_ID = '{{FIREBASE_MESSAGING_SENDER_ID}}';
window.ENV_FIREBASE_APP_ID = '{{FIREBASE_APP_ID}}';
window.ENV_FIREBASE_MEASUREMENT_ID = '{{FIREBASE_MEASUREMENT_ID}}'; 