// This script will run at build time to inject environment variables
// window.ENV_FIREBASE_API_KEY = '{{FIREBASE_API_KEY}}';
// window.ENV_FIREBASE_AUTH_DOMAIN = '{{FIREBASE_AUTH_DOMAIN}}';
// window.ENV_FIREBASE_PROJECT_ID = '{{FIREBASE_PROJECT_ID}}';
// window.ENV_FIREBASE_STORAGE_BUCKET = '{{FIREBASE_STORAGE_BUCKET}}';
// window.ENV_FIREBASE_MESSAGING_SENDER_ID = '{{FIREBASE_MESSAGING_SENDER_ID}}';
// window.ENV_FIREBASE_APP_ID = '{{FIREBASE_APP_ID}}';
// window.ENV_FIREBASE_MEASUREMENT_ID = '{{FIREBASE_MEASUREMENT_ID}}';

// Environment variables for Firebase configuration
window.ENV = {
    FIREBASE_API_KEY: "AIzaSyB-WA4jjwIiy3BoabtKTNC2LYJfweibqI4",
    FIREBASE_AUTH_DOMAIN: "userinfo-10027.firebaseapp.com",
    FIREBASE_PROJECT_ID: "userinfo-10027",
    FIREBASE_STORAGE_BUCKET: "userinfo-10027.firebasestorage.app",
    FIREBASE_MESSAGING_SENDER_ID: "605892604762",
    FIREBASE_APP_ID: "1:605892604762:web:e4e6f1231f144e2e983963",
    FIREBASE_MEASUREMENT_ID: "G-HVK6HKR639"
}; 